### ISSUE TITLE
Stuck user in guild page. 

### ISSUE THREAD

**Issue by SteveDave89** [danpaulson/swgoh.gg.public#196]
We have a member that has never been a part of our guild stuck at the bottom of our roster. His swgoh has been out of sync for over a year. Any help in removing this would be great. 
Roster: https://swgoh.gg/g/13231/gamma-g/
Member in question: https://swgoh.gg/u/clayton/

**Comment by danpaulson** [comment]
This should be fixed.

**Comment by SteveDave89** [comment]
This was not fixed. He is still showing as a profile on our roster.
