### ISSUE TITLE
Search for characters in guild doesn't show ones of new members

### ISSUE THREAD

**Issue by akapes** [danpaulson/swgoh.gg.public#72]
I changed the guild some days ago. 
Meanwhile I have the correct guild name displayed in my profile. 
When I click on the link, I see me as a member of this guild. 
But when I search for a character and who has it in the guild my name never shows up.

**Comment by LeGoZoR** [comment]
Hi there !
Same problem here, the guild page has not been update for 5 days, since the sync problem it seems.
So when I search for a character in the guild, only a 5/50 players appears as result.

**Comment by danpaulson** [comment]
This should be fixed now - but let me know if it's not (with links and data please)

**Comment by angelus359** [comment]
Hi Dan,

I'm still experiencing the same issue.

https://swgoh.gg/u/ganymede/
https://swgoh.gg/g/7126/nerf-herder/

Do a Unit Search for Aayla Secura (who I have at 7 stars) on the guild page and my user account does not show up.

Thanks in advance for your help!

**Comment by danpaulson** [comment]
Thanks for the links and description - I see the issue now. Will fix soon. Your guild should be fixed now.

**Comment by angelus359** [comment]
Yep, it's working for me now. Thanks again!

**Comment by akapes** [comment]
Well done, it's working for me, too. 
Thank you!
